### ISSUE TITLE
Setting up issues

### ISSUE THREAD

**Issue by r3sus** [clienthax/Ps3GhidraScripts#1]
Hello and thanks a lot for your work! 

I followed readme, but `AnalyzePs3Binary.java` script output was [this error.](https://github.com/clienthax/Ps3GhidraScripts/blob/ec79d4d689ea875ee5cc281223a225de26fb9ad7/java/AnalyzePs3Binary.java#L118)

Noteworthy, script didn't asked for `nids.txt` location. 

Script was located in some manually added folder, not in Ghidra scripts folder. As well as `syscall.txt`.

Ghidra 9.2.

Thanks.

**Comment by clienthax** [comment]
What did you attempt to load?
Also did you decrypt the binary before loading it into ghidra

**Comment by r3sus** [comment]
Hello and thanks for a quick response. 
> What did you attempt to load?
PS3 ELF
> Also did you decrypt the binary before loading it into ghidra
Yes

**Comment by clienthax** [comment]
> Hello and thanks for a quick response.
> 
> > What did you attempt to load?
> 
> PS3 ELF
> 
> > Also did you decrypt the binary before loading it into ghidra
> 
> Yes

I meant specifically which binary.., can you add me on discord clienthax#1337

**Comment by clienthax** [comment]
Looks like ghidra have modified the elf header for some reason in the later versions of 9.2, will update soon.

**Comment by VelocityRa** [comment]
Fixed in e040832e81d4bd46fb1cd4b81a245595da8300d6, this can be closed now.
