### ISSUE TITLE
Cannot find elf header of eboot

### ISSUE THREAD

**Issue by GovanifY** [clienthax/Ps3GhidraScripts#20]
Tested on ghidra 10.1.4 using tagged version 1.045.
Trying to run AnalyzePs3Binaries end up in a NullPo at Ps3ElfUtils.java:40:

```java
        this.elfHeader = findElfHeader(); // <- returns NULL
        this.sections = parseSections(script.getDataAt(elfHeader.getStart()));
        programType = findPs3ProgramType();
```

Looking at the file, I can confirm the ELF header is present and can be correctly parsed, although after a 0x90 bytes SCE header.

```
➜ file eboot.bin
eboot.bin: data
➜ cp -rf eboot.bin eboot.elf
➜ r2 -w eboot.elf
 -- r2 is meant to be read by machines.
[0x00000000]> r-0x90
[0x00000000]> q
➜ file eboot.elf
eboot.elf: ELF 64-bit MSB executable, 64-bit PowerPC or cisco 7500, Unspecified or Power ELF V1 ABI, version 1, statically linked, missing section headers at 46090628
```

Ghidra only seems to look at the first block starting at 0x0, failing to find the first ELF header and failing.

**Comment by clienthax** [comment]
You need to decrypt the reboot beforehand.
Try using rpcs3 to decrypt it and see if the elf it outputs loads

**Comment by GovanifY** [comment]
All of this was done on a decrypted eboot.

**Comment by clienthax** [comment]
Rpcs3 

> All of this was done on a decrypted eboot. As you can see above, removing the first 0x90 bytes does make an ELF appear. Furthermore, running `strings` on the file returns a bunch of references

The input elf should not have the sce header as ghidra won't know what to do with it, rpcs3 strips this header

**Comment by GovanifY** [comment]
That seems to have done the trick, sorry about that! I thought decrypted meant strictly decrypting the container, not a full blown ELF stripdown, which was why you made scripts and not plugins.


Thanks a lot for the help and sorry for the bother!
