### ISSUE TITLE
TOC incorrectly parsed on prototype elfs

### ISSUE THREAD

**Issue by Nenkai** [clienthax/Ps3GhidraScripts#5]
Binaries: https://cdn.discordapp.com/attachments/807830839756455937/807855596333563936/GTHD_debug_elf.zip (let me know if it shouldn't be linked here)

It would seem that pre-release/sdk elf builds were organized differently, as the TOC base offset fetched by `AnalyzePs3Binary.java` is not the correct one (real hardware also fails to locate it).

Forcing the script to use a specific toc address somewhat fixes it, only on the dissasembly however.
Certain specific r2 offsets also seem to be incorrect even after manually fixing it.

**Comment by clienthax** [comment]
Havnt looked at the file yet, but iirc prerelease elf's had two toc sections and had named sections,

Will take a look later

**Comment by clienthax** [comment]
These files are very different to the release elfs,
Grab latest release https://github.com/clienthax/Ps3GhidraScripts/releases (its an extension now)
load elf with same instructions but instead of using AnalyzePs3Binary just use auto analysis and then run AsignPs3R2FromOpd
